services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7888:7888"
    networks:
      - secure-paste-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7888/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "6781:80"
    environment:
      - REACT_APP_WEBSOCKET_URL=http://${HOST_IP:-localhost}:7888
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - secure-paste-network

networks:
  secure-paste-network:
    driver: bridge
