# docker-compose.yml
services:
  backend:
    build: ./
    ports:
      - "7878:7878"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "6781:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
