# docker-compose.yml
services:
  backend:
    build: ./secure-paste
    ports:
      - "3001:3001"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_WEBSOCKET_URL=ws://backend:3001
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
